version: 2
jobs:
  build:

    working_directory: ~/serenity.bdd.test

    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: selenium/standalone-chrome:3.11.0


    steps:

      - checkout

      - restore_cache:

          key: serenity.bdd.test-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: serenity.bdd.test-{{ checksum "pom.xml" }}

      - run:
          name: Install latest version of Chrome
          command: |
            sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get -y install google-chrome-stable
            - run:
                name: Use ChromeDriver found in repository
                command: |
                  sudo chmod 777 /home/circleci/circleCiTesting/src/test/resources/chromedriver.exe
                  sudo apt-get install libxi6 libgconf-2-4
                  sudo apt-get -y install xvfb gtk2-engines-pixbuf
                  sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
                  sudo apt-get install xvfb
                  sudo apt-get -y install imagemagick x11-apps

      - run: mvn clean verify

      - store_test_results:
          path: target/failsafe-reports

      - store_artifacts:
          path: target/site/serenity