version: 2
jobs:
  build:

    working_directory: ~/serenity.bdd.test

    docker:
      - image: circleci/openjdk:11.0.2-jdk-stretch-node-browsers-legacy

    steps:

      - checkout

      - restore_cache:

          key: serenity.bdd.test-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: serenity.bdd.test-{{ checksum "pom.xml" }}
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar

      - run:
          name: Start Selenium
          command: |
            mkdir selenium-log
            java -jar selenium-server-standalone-3.5.3.jar -log selenium-log/selenium.log
            background: true

        # run tests!
      - run: mvn clean verify -P it -Dproperties=`pwd`/serenity-integration.properties

      - store_test_results:
          path: target/failsafe-reports

      - store_artifacts:
          path: target/site/serenity

      - store_artifacts:
          path: selenium-log/
          destination: log