version: 2
jobs:
  build:

    working_directory: ~/serenity.bdd.test

    docker:
      - image: circleci/openjdk:8-jdk-stretch



    steps:

      - checkout

      - restore_cache:

          key: serenity.bdd.test-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies



      - run:
          name: Install latest version of ChromeDriver Sample
          command: |
            sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install google-chrome-unstable
      - run:
          name: Install latest version of ChromeDriver Sample
          command: |
            sudo wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
            sudo unzip chromedriver_linux64.zip
            sudo rm chromedriver_linux64.zip
            sudo mv chromedriver /usr/bin/
            sudo chmod 777 /usr/bin/chromedriver
            sudo apt-get install libxi6 libgconf-2-4
            sudo apt-get -y install xvfb gtk2-engines-pixbuf
            sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
            sudo apt-get install xvfb
            sudo apt-get -y install imagemagick x11-apps
      - run:
          name: Running X virtual framebuffer
          command: Xvfb :0 -ac &

      - run:
          name: Run Tests
          command: |
                  export DISPLAY=:99

      - save_cache:
          paths:
            - ~/.m2
          key: serenity.bdd.test-{{ checksum "pom.xml" }}

      - run: mvn clean verify

      - store_test_results:
          path: target/failsafe-reports

      - store_artifacts:
          path: target/site/serenity