version: 2
jobs:
  build:

    working_directory: ~/serenity.bdd.test

    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: selenium/standalone-chrome:3.11.0


    steps:

      - checkout

      - restore_cache:

          key: serenity.bdd.test-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: serenity.bdd.test-{{ checksum "pom.xml" }}

      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar

            - run:
                name: Start Selenium
                command: |
                  java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
                background: true

      - run: mvn clean verify

      - store_test_results:
          path: target/failsafe-reports

      - store_artifacts:
          path: target/site/serenity