version: 2
jobs:
  build:

    working_directory: ~/serenity.bdd.test

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:

          key: serenity.bdd.test-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: serenity.bdd.test-{{ checksum "pom.xml" }}

      - run: mvn clean verify

      - store_test_results:
          path: target/failsafe-reports

      - store_artifacts:
          path: target/site/serenity